{{- range .Values.regionalDR }}
{{- $secretStoreName := .secretStore.name }}
{{- $secretStoreKind := .secretStore.kind }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: {{ .primary.name }} 
spec:
  dataFrom:
  - extract:
      # Expects entries called: aws_access_key_id and aws_secret_access_key
      key: {{ default "secret/hub/aws" .awsKeyPath }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: {{ $secretStoreKind }}
  target:
    name: aws-secret
    creationPolicy: Owner
    template:
      type: Opaque


{{- range .secondaries }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-secret
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: {{ .name }}
spec:
  dataFrom:
  - extract:
      # Expects entries called: aws_access_key_id and aws_secret_access_key
      key: {{ default "secret/hub/aws" .awsKeyPath }}
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: {{ $secretStoreKind }}
  target:
    name: aws-secret
    creationPolicy: Owner
    template:
      type: Opaque
{{- end }}
{{- end }}
